---
title: "Naive Bayes in R"
output: html_notebook
---

```{r}
#references:https://www.geeksforgeeks.org/naive-bayes-classifier-in-r-programming/
library("tidyverse")
library("e1071")
library("caret")
library("caTools")
library("GGally")
library(ggplot2)
library(caret)
library(caretEnsemble)
library(psych)
library(Amelia)
library(mice)
library(GGally)
library(rpart)
library(randomForest)
df = read_csv('C:/Users/dell/Desktop/ANLY501/homework/anly-501-project-acousma48-main/data/cleaning data/twitter_data_clean.csv')
print(df)
df= df%>%
  select(favorite_count,retweet_count,`Whether the relevant`)
split <- sample.split(df$`Whether the relevant`, SplitRatio = 0.5)
train_cl <- subset(df, split == "TRUE")
test_cl <- subset(df, split == "FALSE")
 
# Feature Scaling
train_scale <- scale(train_cl[, 1:3])
test_scale <- scale(test_cl[, 1:3])
 
# Fitting Naive Bayes Model
# to training dataset
set.seed(999)  # Setting Seed
classifier_cl <- naiveBayes(`Whether the relevant` ~ ., data = train_cl)
classifier_cl
# Predicting on test data'
y_pred <- predict(classifier_cl, newdata = test_cl)
 
# Confusion Matrix
cm <- confusionMatrix(data = y_pred,reference = as.factor(test_cl$`Whether the relevant`))
cm
```
```{r}
confusion <- as.data.frame(cm$table)
confusion$Prediction <- factor(confusion$Prediction, levels=rev(levels(confusion$Prediction)))
CPLOT=ggplot(confusion, aes(Prediction,Reference, fill= Freq)) +
        geom_tile() + geom_text(aes(label=Freq)) +
        scale_fill_gradient(low="white", high="purple") +
        labs(x = "Predict Labels",y = "Actual Labels") +
        ggtitle("Confusion Matrix")+
        theme(plot.title = element_text(size = 18, face = "bold"))
CPLOT
ggsave("naive_bayes_R.png",CPLOT, path = "C:/Users/dell/Desktop/ANLY501/homework/anly-501-project-acousma48-main/501-project-website/images",width = 12,height = 10)
```
```{r}
pair = ggpairs(df)
ggsave("pair.png",pair, path = "C:/Users/dell/Desktop/ANLY501/homework/anly-501-project-acousma48-main/501-project-website/images",width = 12,height = 10)
pair
```
